### ISSUE TITLE
JSESSIONID does not exist some times

### ISSUE THREAD

**Issue by Beomi** [Beomi/simple_bank_korea#2]
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lathe\venv\lib\site-packages\simple_bank_korea\kb\crawler.py", line 10, in get_transactions
    VIRTUAL_KEYPAD_INFO = get_keypad_img(PHANTOM_PATH)
  File "C:\Users\lathe\venv\lib\site-packages\simple_bank_korea\kb\image_checker.py", line 23, in get_keypad_img
    JSESSIONID = driver.get_cookie('JSESSIONID').get('value')
AttributeError: 'NoneType' object has no attribute 'get'
```
TODO: return '' if JSESSIONID not exist.

**Comment by Beomi** [comment]
Fixed in v0.2.3
